#spring.data.mongodb.uri=mongodb+srv://nitinmeher844_db_user:pass@cluster0.e4p7wha.mongodb.net/journalDb?retryWrites=true&w=majority&appName=Cluster0
spring.application.name=moodjournal
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=journalDb
spring.data.mongodb.auto-index-creation=true


