Spring:
  Application:
    name: moodjournal
  data:
    mongodb:
      host: localhost
      port: 27017
      database: journalDb
      auto-index-creation: true
weather:
  api:
    key: 0aaf7f041cc74b8f9fb103730262303